//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arkusz_Wydatki_WPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transakcje
    {
        public int Trans_ID { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public int IdUzytkownika { get; set; }
        public int IdKategorii { get; set; }
        public int IdPodkategorii { get; set; }
        public Nullable<double> Kwota { get; set; }
        public Nullable<int> PlanId { get; set; }
    
        public virtual Kategorie Kategorie { get; set; }
        public virtual Podkategorie Podkategorie { get; set; }
        public virtual Uzytkownik Uzytkownik { get; set; }
    }
}
