//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domowe_Wydatki
{
    using System;
    using System.Collections.Generic;
    
    public partial class ePodkategorie
    {
        public int ID { get; set; }
        public Nullable<int> IdKategorii { get; set; }
        public string Podkategoria { get; set; }
    }
}
