// <auto-generated />
using System;
using ArkuszDataBase.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ArkuszDataBase.Migrations
{
    [DbContext(typeof(Arkusz_WydatkiContext))]
    partial class Arkusz_WydatkiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ArkuszDataBase.Models.Kategorie", b =>
                {
                    b.Property<int>("KatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Kat_Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Kategoria")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.HasKey("KatId")
                        .HasName("PK__Kategori__87B3726890867C4A");

                    b.ToTable("Kategorie");
                });

            modelBuilder.Entity("ArkuszDataBase.Models.Plan", b =>
                {
                    b.Property<int>("PlanId")
                        .HasColumnName("Plan_ID");

                    b.Property<decimal?>("FaktycznaKwota")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<int>("IdTransakcji");

                    b.Property<int>("IdUzytkownika");

                    b.Property<DateTime?>("Miesiąc")
                        .HasColumnType("date");

                    b.Property<decimal?>("ZalozonaKwota")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("PlanId");

                    b.HasIndex("IdTransakcji");

                    b.HasIndex("IdUzytkownika");

                    b.ToTable("Plan");
                });

            modelBuilder.Entity("ArkuszDataBase.Models.Podkategorie", b =>
                {
                    b.Property<int>("PodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Pod_ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("IdKategorii");

                    b.Property<string>("Podkategoria")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.HasKey("PodId")
                        .HasName("PK__Podkateg__6680BE6EF145A89C");

                    b.HasIndex("IdKategorii");

                    b.ToTable("Podkategorie");
                });

            modelBuilder.Entity("ArkuszDataBase.Models.Transakcje", b =>
                {
                    b.Property<int>("TransId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Trans_ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Data")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdKategorii");

                    b.Property<int>("IdPodkategorii");

                    b.Property<int>("IdUzytkownika");

                    b.Property<double?>("Kwota");

                    b.HasKey("TransId")
                        .HasName("PK__Transakc__7B615C8D012D977A");

                    b.HasIndex("IdKategorii");

                    b.HasIndex("IdPodkategorii");

                    b.HasIndex("IdUzytkownika");

                    b.ToTable("Transakcje");
                });

            modelBuilder.Entity("ArkuszDataBase.Models.Uzytkownik", b =>
                {
                    b.Property<int>("UzytId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Uzyt_ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DataDodania")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("DataUsuniecia");

                    b.Property<string>("EMail")
                        .HasColumnName("e_mail")
                        .HasMaxLength(50);

                    b.Property<string>("Imie")
                        .HasMaxLength(30);

                    b.Property<string>("Nazwisko")
                        .HasMaxLength(50);

                    b.Property<string>("Nick")
                        .HasMaxLength(30);

                    b.Property<DateTime?>("OstatnieLogowanie")
                        .HasColumnType("datetime");

                    b.HasKey("UzytId")
                        .HasName("PK__Uzytkown__866806738B051B36");

                    b.ToTable("Uzytkownik");
                });

            modelBuilder.Entity("ArkuszDataBase.Models.Plan", b =>
                {
                    b.HasOne("ArkuszDataBase.Models.Transakcje", "IdTransakcjiNavigation")
                        .WithMany("Plan")
                        .HasForeignKey("IdTransakcji")
                        .HasConstraintName("FKTransakcja");

                    b.HasOne("ArkuszDataBase.Models.Uzytkownik", "IdUzytkownikaNavigation")
                        .WithMany("Plan")
                        .HasForeignKey("IdUzytkownika")
                        .HasConstraintName("FKPlanUzytkownik");
                });

            modelBuilder.Entity("ArkuszDataBase.Models.Podkategorie", b =>
                {
                    b.HasOne("ArkuszDataBase.Models.Kategorie", "IdKategoriiNavigation")
                        .WithMany("Podkategorie")
                        .HasForeignKey("IdKategorii")
                        .HasConstraintName("FKPKategoria");
                });

            modelBuilder.Entity("ArkuszDataBase.Models.Transakcje", b =>
                {
                    b.HasOne("ArkuszDataBase.Models.Kategorie", "IdKategoriiNavigation")
                        .WithMany("Transakcje")
                        .HasForeignKey("IdKategorii")
                        .HasConstraintName("FKKategoria");

                    b.HasOne("ArkuszDataBase.Models.Podkategorie", "IdPodkategoriiNavigation")
                        .WithMany("Transakcje")
                        .HasForeignKey("IdPodkategorii")
                        .HasConstraintName("FKPodKategoria");

                    b.HasOne("ArkuszDataBase.Models.Uzytkownik", "IdUzytkownikaNavigation")
                        .WithMany("Transakcje")
                        .HasForeignKey("IdUzytkownika")
                        .HasConstraintName("FKUzytkownik");
                });
#pragma warning restore 612, 618
        }
    }
}
