//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domowe_Wydatki
{
    using System;
    using System.Collections.Generic;
    
    public partial class eZestawienie
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public int IdAutora { get; set; }
        public int IdKategorii { get; set; }
        public int IdPodkategorii { get; set; }
        public Nullable<double> Kwota { get; set; }
    }
}
